"""Regenerate the three checked-in, output-free tutorial notebooks."""
from pathlib import Path
import json
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]


def write(name, cells):
    book = nbf.v4.new_notebook()
    book.metadata = {"kernelspec": {"display_name": "Python (Pyodide)", "language": "python", "name": "python"}, "language_info": {"name": "python"}}
    book.cells = [(nbf.v4.new_markdown_cell if kind == "md" else nbf.v4.new_code_cell)(source) for kind, source in cells]
    # Stable ids keep regeneration reviewable.
    for number, cell in enumerate(book.cells):
        cell.id = f"{name[:2]}-cell-{number:02}"
    # ASCII escapes avoid platform-default encoding corruption in Lite contents.
    (ROOT / "notebooks" / name).write_text(json.dumps(book, indent=1, ensure_ascii=True) + "\n", encoding="utf-8")


write("01_launch_map.ipynb", [
    ("md", "# 1 · Launch the map\n\nThis notebook runs in **JupyterLite with a Pyodide kernel**, entirely in your browser. Use **Run → Run All Cells**. The first kernel start downloads a WebAssembly runtime and may take a minute. No account or backend Python service is involved.\n\nThe explorer connects directly to WorldPop. Pan or zoom, choose a collection (country ISO3 codes such as `UGA`), use the map extent, and search. Footprints describe **metadata coverage, not population values**."),
    ("code", "import sys\nprint('Python', sys.version.split()[0], '· browser runtime' if sys.platform == 'emscripten' else '· local runtime')\nfrom stac_browser import explorer_url\nfrom IPython.display import IFrame, display\ndisplay(IFrame(src=explorer_url(), width='100%', height=820))"),
    ("md", "## Try a discovery\n\n1. Keep the WorldPop preset and choose `UGA`, or search all collections.\n2. Move the map to East Africa and click **Use map extent**.\n3. Click **Search this area**, then select a result or footprint.\n4. Inspect providers, license, source links, and asset media types.\n5. Export GeoJSON and Search JSON. The asset links may point to large rasters; none are downloaded automatically.\n\nIf an embedded map is cramped, open the Explorer link in the site navigation. Continue with `02_worldpop_search.ipynb` to reproduce a query in Python. Browser downloads and notebook files are separate: right-click saved files in the JupyterLite file browser and choose **Download** to keep a durable copy."),
])
write("02_worldpop_search.ipynb", [
    ("md", "# 2 · Search WorldPop with browser Python\n\nThis tutorial uses the same HTTPS STAC API as the map. The async helper uses `pyodide.http.pyfetch` inside Pyodide. In normal Python it uses a standard-library adapter for local tests. Browser CORS still applies. Run the cells in order; if the provider is unavailable, rerun the connection cell later. No credentials are needed."),
    ("code", "from stac_browser import STACBrowser, PRESETS\nclient = await STACBrowser(PRESETS['worldpop']).connect()\nprint(client.root.get('title', client.root['id']))\nprint(len(client.collections), 'collections loaded')\n[(c['id'], c.get('title', c['id'])) for c in client.collections[:8]]"),
    ("md", "## A bounded query\n\nThis rectangle covers Uganda and nearby areas. `bbox` is **west, south, east, north**, in WGS84 longitude/latitude. The collection ID is a country ISO3 code; WorldPop datetime can be a release date: inspect properties.year for the population reference year. The page limit is 5. Remove dates or broaden the bbox when no items match."),
    ("code", "items = await client.search(bbox=[29, -2, 35, 5], collection='UGA', limit=5)\nprint(len(items), 'items loaded')\nfor item in items:\n    print(item['id'], item['properties'].get('year'), item['properties'].get('project'), item['properties'].get('datetime'), list(item.get('assets', {})))"),
    ("md", "## Preserve attribution and provenance\n\nItems retain their original properties, links, and assets. Consult the collection's license and providers before downloading or publishing any data. This project’s MIT software license does not replace dataset licenses."),
    ("code", "collection = next((c for c in client.collections if c['id'] == 'UGA'), {})\nprint('License:', collection.get('license', 'consult provider'))\nprint('Providers:', collection.get('providers', []))\nif items:\n    client.save('worldpop')\n    print('Saved worldpop-items.geojson and worldpop-search.json. Download them from the file browser.')\nelse:\n    print('No data exported: broaden the query and retry.')\nclient.provenance()"),
    ("md", "## Load another page deliberately\n\nCall `await client.more()` to load exactly one next page. It follows advertised GET/POST pagination, deduplicates collection/item IDs, and caps results at 500. It never walks every page automatically. To download your results, use the file browser’s Download command; browser storage can be cleared."),
])
write("03_other_catalogs_and_export.ipynb", [
    ("md", "# 3 · Other catalogs and reusable exports\n\nEarth Search and Planetary Computer are included as public STAC API presets. A custom root must use HTTPS, return a STAC Catalog or Collection, and allow browser CORS. Public metadata access does not guarantee unrestricted asset access; some Planetary Computer assets require separate signing. This notebook does not fetch raster assets."),
    ("code", "from stac_browser import STACBrowser, PRESETS\nclient = await STACBrowser(PRESETS['earthsearch']).connect()\nprint('Catalog:', client.root.get('title', client.root['id']))\nprint('Collections:', [c['id'] for c in client.collections])"),
    ("code", "items = await client.search(bbox=[-123.1, 37.2, -121.8, 38.1], collection='sentinel-2-l2a', start='2024-06-01', end='2024-06-15', limit=3)\nprint(len(items), 'items loaded')\nif items:\n    client.save('earthsearch')\n    print('Saved earthsearch-items.geojson and earthsearch-search.json')"),
    ("md", "## Reuse exported search JSON\n\nThe map and Python helper export `stac_root`, `query`, `requests`, retrieval time, and count. Upload the downloaded JSON to JupyterLite. Replace `saved` below with `json.loads(Path('stac-search.json').read_text(encoding='utf-8'))` to reuse an exported query. Dates come from the inclusive day interval exported by this project.\n\nStatic-item exports have `query: null`: their provenance records the item GET request instead of an API search. The replay helper handles that branch first and returns the loaded item as a one-element list. API exports repeat the first search page; call `more()` on a connected client to request further pages. GeoJSON export copies resolve relative links to absolute URLs while the client retains the original metadata."),
    ("code", "import json\nfrom pathlib import Path\nsaved = client.provenance()\nprint('Source root:', saved['stac_root'])\nprint('Reproducible query:', saved.get('query'))\n\nasync def replay_saved(saved):\n    replay = await STACBrowser(saved['stac_root']).connect()\n    query = saved.get('query')\n    if query is None:\n        requests = saved.get('requests') or []\n        if not requests or requests[-1].get('method', 'GET').upper() != 'GET':\n            raise ValueError('Static-item replay requires an exported item GET request.')\n        await replay.open_link({'rel': 'item', 'href': requests[-1]['url']})\n        return replay.items\n    dates = query.get('datetime', '../..').split('/')\n    return await replay.search(\n        bbox=query['bbox'], collection=(query.get('collections') or [None])[0],\n        start=None if dates[0] == '..' else dates[0][:10],\n        end=None if dates[1] == '..' else dates[1][:10], limit=query['limit'])\n\n# To issue the saved request again (new HTTP requests), uncomment:\n# replay_items = await replay_saved(saved)"),
    ("md", "## Static catalogs are different\n\nA static Catalog/Collection may have `child` and `item` links without a remote `search` endpoint. Connect with `await STACBrowser('https://.../catalog.json').connect()`, inspect `client.browse_links()`, and pass a selected link to `await client.open_link(link)`. Child links return another connected browser; item links load one item for export. This does not pretend to provide server-side search or recursively crawl the catalog.\n\n## Troubleshooting\n\nA request failure can mean CORS, offline networking, an invalid TLS certificate, a provider error, or non-JSON content. There is no CORS bypass. Correct the URL, choose another preset, or retry later. Dates, bbox order, and page sizes are validated before requests. The map’s **Field guide** link includes architecture and references."),
])
